### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-ruby-laptop-setup#1]
Hey @egillespie, can you take a look at this? It's [hosted here](https://evening-ocean-71772.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/ruby-laptop-setup/1) criteria:
- [x] push Heroku's sample app to GitHub
- [x] host Heroku's sample app on Heroku

**Comment by ackleyd1** [comment]
https://ravedave.herokuapp.com/

**Comment by egillespie** [comment]
Legit. :shipit:

Just a heads up, once you get a few lessons deep into Ruby you will need to login to Heroku to remove old apps.
